site_name: FitBook
nav:
  - Home: index.md
  - Segni Vitali: vitali.md
  - Direttive OMS: OMS.md
  - Suggerimenti: suggerimenti.md
theme:
  name: material
  language: it
extra:
  generator: false

use_directory_urls: false